### ISSUE TITLE
AlgorithmAnalysisExamples.rst - self-check exercises are written in cpp

### ISSUE THREAD

**Issue by powderflask** [pearcej/complex#237]
Wondering if this is the right repo to make pull-requests to when I find small errors like this?
So very happy to see this marvelous text added to Runestone collection, and will be using this version next term.  Willing to fix any issues I come across,  just want to get them to the right repo.  thank!

**Comment by pearcej** [comment]
@powderflask  Happy New Year!

I agree that this is a great book! I would very much welcome pull-requests, and yes, this is the right repo for them.

**Comment by powderflask** [comment]
I wanted to make a simple PR to get started and will package up more patches in any future PRs.  

But I'm having trouble with my local build...  
`runestone build` works fine, reports some DB warnings (which I found I could ignore) and this warning `WARNING: html_static_path entry '_sources/_static' does not exist` which I assume is just b/c there's no local static files.

But the resulting html in build/complex  appears to contain uninterpreted template code / variables, E.g.
`   
 eBookConfig.course = '{{ course_name }}';
`
and
`
{% if serve_ad is defined and serve_ad and settings.adsenseid %}
`
Those in turn cause JS to errors when page is loaded, and so the page loads, but without any of the active components.  Before I start digging deep here, hoping someone recognizes what I've done wrong and can offer some advice to get me going again.  Thanks.
